version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.IdentityModel.Tokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 5.6.3
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Microsoft.AspNetCore.SpaServices
    versions:
    - 3.1.11
    - 3.1.12
    - 3.1.13
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
- package-ecosystem: npm
  directory: "/src/King.David.Consulting.Travel"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 0.28.11
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: bootstrap
    versions:
    - 3.4.1
  - dependency-name: url-loader
    versions:
    - 0.6.2
